# Generated by Django 4.1.1 on 2022-09-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('price', models.PositiveBigIntegerField()),
                ('color', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
            ],
        ),
    ]
