import type { NextPage } from "next";
import Head from "next/head";
import {AppBar, Box, Typography, Toolbar, IconButton, Button} from "@mui/material";
import MenuIcon from '@mui/icons-material/Menu';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Selmi Cars</title>
        <meta name="description" content="Generated by create next app" />
        {/*<link rel="icon" href="/favicon.ico" />*/}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <Box sx={{ flexGrow: 1 }}>
      <AppBar position="static">
        <Toolbar>
          <IconButton
            size="large"
            edge="start"
            color="inherit"
            aria-label="menu"
            sx={{ mr: 2 }}
          >
            <MenuIcon />
          </IconButton>
          <Typography color="yellow" variant="h6" component="div" sx={{ flexGrow: 1 }}>
            Selmi Cars
          </Typography>
          <Button color="inherit">Login</Button>
            <Button color="inherit">Register</Button>
        </Toolbar>
      </AppBar>
    </Box>
    </div>
  );
};

export default Home;
