import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Appnavbar from "../components/layout/navbar";
import Appcarousel from "../components/layout/appcarousel";
import "bootstrap/dist/css/bootstrap.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Appnavbar />
      <main>
        <Appcarousel />
      </main>
    </div>
  );
}
